# Generated by Django 4.2.5 on 2023-09-16 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ex01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvoted_tips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tip',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_tips', to=settings.AUTH_USER_MODEL),
        ),
    ]
